"""books table and relation to authors

Revision ID: dfc4e39be19d
Revises: 
Create Date: 2022-11-09 21:23:41.106446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc4e39be19d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_gender'), 'author', ['gender'], unique=False)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_index(op.f('ix_author_nationality'), 'author', ['nationality'], unique=False)
    op.create_table('borrowed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowed_status'), 'borrowed', ['status'], unique=False)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('borrow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['borrow_id'], ['borrowed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_genre'), 'book', ['genre'], unique=False)
    op.create_index(op.f('ix_book_language'), 'book', ['language'], unique=False)
    op.create_index(op.f('ix_book_pages'), 'book', ['pages'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_table('CONNECTED',
    sa.Column('authorID', sa.Integer(), nullable=False),
    sa.Column('bookID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorID'], ['author.id'], ),
    sa.ForeignKeyConstraint(['bookID'], ['book.id'], ),
    sa.PrimaryKeyConstraint('authorID', 'bookID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CONNECTED')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_pages'), table_name='book')
    op.drop_index(op.f('ix_book_language'), table_name='book')
    op.drop_index(op.f('ix_book_genre'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_borrowed_status'), table_name='borrowed')
    op.drop_table('borrowed')
    op.drop_index(op.f('ix_author_nationality'), table_name='author')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_gender'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
